version: "3.7"

services:
  bitbucket:
    container_name: bitbucket
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - /var/atlassian/application-data/bitbucket:/var/atlassian/application-data/bitbucket
    ports:
      - 7990:7990
